In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import control
from numpy import sin, cos, tan, pi
from control import TransferFunction as TF

# Scientic/Engineering Python

- plotting
- working with arrays
    - slicing and indexing
- `glob`
- `np.loadtxt`

# Basics of plotting

- put all commands related to one plot in one cell
- use `plt.figure()` to create the plot
- use `plt.plot(x,y)` to add a line to a plot
- [https://matplotlib.org/tutorials/index.html](https://matplotlib.org/tutorials/index.html) has many demos and tutorials

In [2]:
help(plt.plot)

Help on function plot in module matplotlib.pyplot:

plot(*args: 'float | ArrayLike | str', scalex: 'bool' = True, scaley: 'bool' = True, data=None, **kwargs) -> 'list[Line2D]'
    Plot y versus x as lines and/or markers.

    Call signatures::

        plot([x], y, [fmt], *, data=None, **kwargs)
        plot([x], y, [fmt], [x2], y2, [fmt2], ..., **kwargs)

    The coordinates of the points or line nodes are given by *x*, *y*.

    The optional parameter *fmt* is a convenient way for defining basic
    formatting like color, marker and linestyle. It's a shortcut string
    notation described in the *Notes* section below.

    >>> plot(x, y)        # plot x and y using default line style and color
    >>> plot(x, y, 'bo')  # plot x and y using blue circle markers
    >>> plot(y)           # plot y using x as index array 0..N-1
    >>> plot(y, 'r+')     # ditto, but with red plusses

    You can use `.Line2D` properties as keyword arguments for more
    control on the appearance. Line pro

# Creating arrays

- multiple ways to create arrays:
    - pass a list or a list of lists into `np.array`
    - use `np.arange` to create a vector with constant steps (a time vector)
    - use `np.zeros` or `np.eye` to create an array of zeros or an identity matrix
        - then replace the elements you want to change

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [4]:
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [6]:
t = np.arange(0,1,0.1)
t

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [4]:
array3 = np.zeros((3,3))
array3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array3[1,1] = 7
array3

array([[0., 0., 0.],
       [0., 7., 0.],
       [0., 0., 0.]])

In [7]:
array4 = np.eye(3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
array4[0,1] = np.cos(30*np.pi/180)
array4

array([[1.       , 0.8660254, 0.       ],
       [0.       , 1.       , 0.       ],
       [0.       , 0.       , 1.       ]])

# Slicing and Indexing

In [12]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
A[0,0]

1

In [14]:
A[1,1]

5

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
A[:,0]

array([1, 4, 7])

In [16]:
A[0,:]

array([1, 2, 3])

In [20]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
A[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
A[:,-1]

array([3, 6, 9])