# Intro to Python

## This presentation was auto-generated from a Jupyter notebook

- all I did was write the Python code

# Keys to a new language

- basic syntax
- creating variables
- `for`, `if`, `while`, ...
- creating functions
- importing libraries

# Engineering programming requirements

- graphing
- creating vectors and matrices
- various math/analysis

# Creating Variables

- python is dynamically typed (like Matlab), so you do not need to declare variables in advance

In [4]:
a = 7
b = 1.2
c = a+b
c

8.2

In [3]:
c

8.2

In [1]:
a = 7
b = 1.2
c = a+b

# Basic Syntax: Tab in and Tab out

- after `if` or `for` or the start of a function, tab in (indent)
- tab out at the end (out-dent?)
- there is no need for `end if` or `end for` or curly brackets

```
for(i=1;i<11;i++){
    printf("i = %d\n",i);
}
```

In [7]:
for i in range(1,11):
    print("i = %d" % i)
    print("still in loop")

print("done with loop")

i = 1
still in loop
i = 2
still in loop
i = 3
still in loop
i = 4
still in loop
i = 5
still in loop
i = 6
still in loop
i = 7
still in loop
i = 8
still in loop
i = 9
still in loop
i = 10
still in loop
done with loop


In [8]:
if a > 2:
    print('yes')
    d = 5
else:
    print('no')
    d = -2

yes


# Magical Incantation

- Importing is kind of like `#include` in C
- python gains most of its power by importing modules
- `numpy` provides arrays and many engineering tools
- `matplotlib` provides plotting
- You probably want to create a bookmark to a Jupyter notebook that contains your standard imports

In [13]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi

# Lists vs. Arrays

- standard Python supports lists
- lists are probably not familiar
    - mixed data and variable length
- numpy introduces arrays 
- arrays can be used as vectors and matrices and are better for most analysis

# Creating a list

- lists can contain mixed data types
- lists do not need an initial length and can be appended

In [7]:
list1 = [1,2,3,4]
list2 = ['hello','world',7,9]

In [8]:
list1

[1, 2, 3, 4]

In [9]:
list2

['hello', 'world', 7, 9]

In [10]:
list2

['hello', 'world', 7, 9]

In [11]:
list2.append('sup')
list2

['hello', 'world', 7, 9, 'sup']

In [14]:
myarray = np.array([1,2,3,4])
myarray

array([1, 2, 3, 4])

In [15]:
list1

[1, 2, 3, 4]

In [16]:
myarray*2

array([2, 4, 6, 8])

In [17]:
list1*2

[1, 2, 3, 4, 1, 2, 3, 4]

# range

- built-in function for creating a list of integers
- often used as an index for `for` loops or other things
- note that is stops one value short of what you probably expect

In [18]:
list3 = range(5)#slightly weird python3 thing
list3

range(0, 5)

In [19]:
list(range(5))

[0, 1, 2, 3, 4]

- a range object can be iterated over in a `for` loop
- python3 avoids creating the entire list in RAM in case the list is really long
- the `range` object behaves like a regular list but uses less RAM and prints a little funny

# List functions

- extracting an item or multiple items from a list is called slicing
- slicing uses square brackets like C, rather than parentheses like Matlab
- `len` finds the length of the list

In [13]:
list3 = list(range(5))
list3

[0, 1, 2, 3, 4]

In [16]:
list3[2]

2

In [15]:
list3[1:3]

[1, 2]

# range continued

In [22]:
list4 = list(range(5))
list4

[0, 1, 2, 3, 4]

In [23]:
list5 = list(range(2,7))
list5

[2, 3, 4, 5, 6]

# Creating an array


In [5]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [15]:
array2 = np.array(list1)
array2

array([1, 2, 3, 4])

In [16]:
array3 = np.zeros(5)
array3

array([0., 0., 0., 0., 0.])

# Creating a 2D array

In [2]:
array4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.arange

- a function from numpy for creating arrays with a certain step size
- `new_array = np.arange(start, stop, step)`

In [17]:
array4 = np.arange(0,1,0.1)
array4

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# Lists vs. Arrays

In [6]:
list1

[1, 2, 3, 4]

In [7]:
list1*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
array1

array([1, 2, 3, 4])

In [9]:
array1*2

array([2, 4, 6, 8])

# List vs Arrays Conclussion

- use arrays for numeric analysis, vectors, and matrices
- use lists for non-numeric data (filenames, other strings, ...)
- sometimes use lists to build up an unknown number of things
    - use `np.array(mylist)` to convert the list to an array if needed
- arrays can be 2D (i.e. matrices); nested lists are a bit clumsy

# For loops

- Python `for` loops look weird at first
- it looks too simple; something must be missing
- but what if I really need access to the loop counter/index?

In [20]:
mylist = [1,'hello',3,4]

for item in mylist:
    print('item = %s' % item)

item = 1
item = hello
item = 3
item = 4


In [21]:
N = len(mylist)

for i in range(N):
    item = mylist[i]
    print('item = %s' % item)

item = 1
item = hello
item = 3
item = 4


# A second example

In [18]:
filenames = ['data_file1.csv','data_file2.csv', \
             'data_file3.csv']

for fn in filenames:
    print('loading file %s' % fn)

loading file data_file1.csv
loading file data_file2.csv
loading file data_file3.csv


# The hard way

In [19]:
N = len(filenames)
print('N = %i' % N)

for i in range(N):
    fn = filenames[i]
    print('i = %i, loading file %s' % (i, fn))

N = 3
i = 0, loading file data_file1.csv
i = 1, loading file data_file2.csv
i = 2, loading file data_file3.csv


# Enumerate

- for when you really need access to the loop counter

In [20]:
for i, fn in enumerate(filenames):
    print('i = %i, loading file %s' % (i, fn))

i = 0, loading file data_file1.csv
i = 1, loading file data_file2.csv
i = 2, loading file data_file3.csv


# While loops

In [22]:
a = 1

while a < 5:
    print('a = %s' % a)
    a += 1

a = 1
a = 2
a = 3
a = 4


# Defining functions

In [14]:
def myfunc(a,b):
    c = a + b
    return c

In [15]:
myfunc(2,3)

5

In [23]:
def myfunc2(a, b):
    c = a+b
    d = a*b
    return c, d

In [24]:
out = myfunc2(2,3)
print("out = %s, %s" % (out[0],out[1]))
print("out = " + str(out))

out = 5, 6
out = (5, 6)


In [25]:
def myfunc3(a, b=7):
    return a+b

In [26]:
myfunc3(3)

10

In [27]:
myfunc3(3,4)

7

In [28]:
myfunc3(4, b=5)

9

# Jupyter Notebook tips

- use shift+enter to execute a cell
- take advantage of tab completion
- there are two modes of operation: editting mode and command mode
    - pressing esc sends you to command mode
- command mode keyboard short cuts:
    - a - add cell above
    - b - add cell below
    - m - convert cell to markdown
    - dd - delete current cell
- note the keyboard shortcuts icon

# Markdown is awesome

- markdown is much more powerful than just putting comments in your code
- this text is written in Markdown
- equations are also supported along with including images

$$G(s) = \frac{\omega_n^2}{s^2+2 \zeta \omega_n s + \omega_n^2}$$

- [markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)


## Help and ??

In [27]:
import glob
help(glob.glob)

Help on function glob in module glob:

glob(pathname, *, recursive=False)
    Return a list of paths matching a pathname pattern.
    
    The pattern may contain simple shell-style wildcards a la
    fnmatch. However, unlike fnmatch, filenames starting with a
    dot are special cases that are not matched by '*' and '?'
    patterns.
    
    If recursive is true, the pattern '**' will match any files and
    zero or more directories and subdirectories.



In [2]:
import glob

In [33]:
glob.glob??

# Debugging Tools

- use pdb.set_trace() to set a stopping point in your code
- use `n`, `s`, and `c` to navigate in the debugger
    - `n` = next 
    - `s` = step (into a function)
    - `c` = continue
    - 'l' = list (lower case L, where are you in the code)
- use `q` to quit (exit)