# Slicing Arrays

One thing we need to do often in 345 is extract rows or columns from a matrix of data.  `numpy` is the Python module that handles arrays (vectors, matrices, ....) and many other engineering and scientific stuff.  In `numpy`, vector and matrices are considered `arrays`; a vector is a 1D `array` and a matrix is a 2D `array`.

### Slicing or Indexing

In Python, extract something from a list is called slicing or indexing.  Indexing refers to extracting just one thing and slicing refers to grab more than one thing:

In [3]:
mylist = [0,1,2,3,4,5]

##### Indexing:

In [4]:
mylist[3]

3

##### Slicing:

In [6]:
mylist[2:4]

[2, 3]

#### Slicing Notes

Note that slicing takes the form `mylist[start:stop]`.  Also note that it stops one element before `stop`.

##### Defaults

If `start` is skipped, it default to zero.  If stop is skipped it defaults to the end of the array:

In [7]:
mylist[:3]

[0, 1, 2]

In [8]:
mylist[3:]

[3, 4, 5]

Also note that if I skip both the `start` and the `stop` value, it defaults to the beginning and end, giving me the entire list:

In [14]:
mylist[:]

[0, 1, 2, 3, 4, 5]

##### Negative Indices

Also note that negative indices are supported.  `-1` means the last element in the list:

In [9]:
mylist[-1]

5

and you can use negative indices in slices as well:

In [10]:
mylist[-2:]

[4, 5]

## Slicing 2D Arrays

When we apply slicing to 2D array, we pass in the `start` and `stop` indices for the rows and the columns seperated by a comma:

~~~
myarray[row_start:row_stop,column_start:column_stop]
~~~

In [11]:
import numpy as np

In [12]:
myarray = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
myarray[0,0]

1

In [17]:
myarray[1,1:3]

array([5, 6])

##### Defaults

If I want to extract an entire row or column, I can take advantage of the defaults by passing in just a colon to get either an entire row or an entire column:

The first row:

In [18]:
myarray[0,:]

array([1, 2, 3])

The first column

In [19]:
myarray[:,0]

array([ 1,  4,  7, 10])

All rows except the first and all columns:

In [20]:
myarray[1:,:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Just the last row:

In [21]:
myarray[-1,:]

array([10, 11, 12])

The last two columns:

In [22]:
myarray[:,-2:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

### Exercises

- extract the middle two rows from `myarray`
- extract all columns except the first from `myarray`